using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Todo.UI.Models
{
    /// <summary>
    /// Todo details model
    /// </summary>
    public class TodoItem
    {
        /// <summary>
        /// Id of the Todo Item.
        /// If not provided, this will be autogenerated to a new guid.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Title of Todo item
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Todo Notes
        /// </summary>
        public string Notes { get; set; }

        /// <summary>
        /// User Id
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// Image Url
        /// </summary>
        public System.Uri ImageUrl { get; set; }

        /// <summary>
        /// Tumbnil Image Url
        /// </summary>
        public System.Uri TumbnilUrl { get; set; }

        /// <summary>
        /// Version of the Todo item
        /// </summary>
        public string Version { get; set; }

        public bool Completed { get; set; }
    }
}